### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by Treyyay** [obamadevelopment/client#11]
**Describe the bug**
It crashes whenever I try to run it.

**To Reproduce**
1. Go to put the ObamaHack jar in your mods folder
2. Launch the game
3. See a crash

**Expected behavior**
I expected it to not crash

**Screenshots**
https://prnt.sc/sn2pmg

**Additional context**
just put it in my mods floder. then it crashed when i was trying to run it. The crash happened immediatly.

**Comment by ollieobama** [comment]
What other mods are you using? Make sure no kami, kami blue or any kami or kami blue skids are in there as well as ObamaHack.
