### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by frank157** [obamadevelopment/client#3]
whenever i go above 127y its like i have blindness.

**Comment by YuPr0** [comment]
Turning off anti fog worked for me

**Comment by frank157** [comment]
Ok thanks a lot also do you know how to get rid of keybinds

**Comment by Katatje** [comment]
click to bind a key then press delete or back

**Comment by Katatje** [comment]
not sure which one

**Comment by ollieobama** [comment]
right click module, press bind then backspace

**Comment by frank157** [comment]
Thanks
