### ISSUE TITLE
Gui scale glitch

### ISSUE THREAD

**Issue by YuPr0** [obamadevelopment/client#5]
If I set GUI scale to auto, the client won't fit on the screen, even if I turn it to normal and drag everything where I can see it in auto, won't fit at all and it's unusable if I don't set GUI scale to normal

**Comment by Katatje** [comment]
get a bigger monitor

**Comment by YuPr0** [comment]
Its not cos monitor

**Comment by Katatje** [comment]
yes its because your monitor is tiny

**Comment by YuPr0** [comment]
Its 4k tf do you mean, a gui should fit nicely

**Comment by Katatje** [comment]
yes

**Comment by Katatje** [comment]
set the gui scale to normal

**Comment by YuPr0** [comment]
If I do that everything is tiny in mc and its annoying

**Comment by Katatje** [comment]
same thing with other kami pastes?

**Comment by YuPr0** [comment]
No, only obama

**Comment by ollieobama** [comment]
i highly doubt that is the case, set it to normal, drag all the categories to the area you can see and resize.
